#!/bin/bash
A="/Volumes/iMacSys/CLAUDE AI/SMEsPlus18/odoo-18.0+e.20250608/odoo/addons/account"
cd "$A" || exit 1
F18="models/account_account.py models/account_account_tag.py models/account_root.py models/account_code_mapping.py models/account_journal.py models/account_move.py models/account_move_line.py models/account_full_reconcile.py models/account_partial_reconcile.py models/account_lock_exception.py models/sequence_mixin.py wizard/setup_wizards.py wizard/account_move_reversal.py wizard/account_resequence.py wizard/account_automatic_entry_wizard.py wizard/account_secure_entries_wizard.py wizard/account_merge_wizard.py wizard/account_validate_account_move.py"
echo "P-14 files:            $(echo $F18 | wc -w | tr -d ' ')"
echo "P-14 lines:            $(cat $F18 | wc -l | tr -d ' ')"
echo "P-14a def count:       $(grep -hE '^\s+def ' $F18 | wc -l | tr -d ' ')"
echo "P-10 field decls:      $(grep -hE '^\s+[a-z_0-9]+ = fields\.' $F18 | wc -l | tr -d ' ')"
echo "P-23 raise sites:      $(grep -hE 'raise (UserError|ValidationError|RedirectWarning|AccessError)' $F18 | wc -l | tr -d ' ')"
echo "P-15a api.constrains:  $(grep -hE '@api\.constrains' $F18 | wc -l | tr -d ' ')"
echo "P-15 sqlconstr blocks: $(grep -hE '_sql_constraints = ' $F18 | wc -l | tr -d ' ')"
echo "P-16 access rows:      $(( $(wc -l < security/ir.model.access.csv) - 1 ))"
echo "P-16a ir.rule (addon): $(grep -h 'model=\"ir.rule\"' security/*.xml | wc -l | tr -d ' ')"
echo "P-09a menuitems:       $(grep -h '<menuitem' views/*.xml | wc -l | tr -d ' ')"
echo "P-09b ir.ui.view:      $(grep -h 'model=\"ir.ui.view\"' views/*.xml | wc -l | tr -d ' ')"
echo "P-11 act_window:       $(grep -h 'model=\"ir.actions.act_window\"' views/*.xml wizard/*.xml 2>/dev/null | wc -l | tr -d ' ')"
echo "P-21b sudo (models/):  $(grep -rhE '\.sudo\(' models/ | wc -l | tr -d ' ')"
echo "P-21d cr.execute:      $(grep -rhE 'cr\.execute|_cr\.execute' models/ | wc -l | tr -d ' ')"
echo "P-21a checkcompanydom: $(grep -rhE '_check_company_domain = |def _check_company_domain' . --include='*.py' | grep -v tests | wc -l | tr -d ' ')"
echo "P-13 models in addon:  $(grep -rhE \"^\\s+_name = '\" models/ wizard/ report/ | sort -u | wc -l | tr -d ' ')"
echo "P-20a ir.cron (addon): $(grep -rh 'model=\"ir.cron\"' data/*.xml 2>/dev/null | wc -l | tr -d ' ')"
echo "P-10a get_param keys (single-line pattern): $(grep -rhoE \"get_param\\(\\s*'[a-z_.]+'\" models/ wizard/ | sort -u | wc -l | tr -d ' ')"
echo "P-10a get_param keys (multi-line tolerant):  $(grep -rhoE \"'(account|sequence)\\.[a-z_.]+'\" models/ wizard/ | grep -v 'account\\.move\\|account\\.journal\\|account\\.account\\|account\\.tax\\|account\\.group\\|account\\.report\\|account\\.payment\\|account\\.bank\\|account\\.full\\|account\\.partial\\|account\\.analytic\\|account\\.fiscal\\|account\\.cash\\|account\\.code\\|account\\.root\\|account\\.reconcile\\|account\\.incoterms\\|account\\.lock\\|account\\.secure\\|account\\.merge\\|account\\.automatic\\|account\\.resequence\\|account\\.financial\\|account\\.setup\\|account\\.edi\\|account\\.online' | sort -u | wc -l | tr -d ' ')"
